title: Clinical Bytes
description: >- 
  Welcome to Clinical Bytes, your go-to resource for insightful and practical knowledge in the field of medicine.
  Whether you are an MBBS student, a healthcare professional, or someone passionate about medical sciences,
  Clinical Bytes offers curated content that bridges the gap between theory and clinical practice.
  Explore articles, case studies, and tutorials aimed at enhancing your understanding of patient care, medical procedures, and the latest in medical education
baseurl: "" # leave this blank if you're not using a subdirectory
url: "https://prabhatsharm007.github.io" # replace with your GitHub Pages URL
theme: minima # basic theme to get you started
